name: BenKahre
favicon: null
layout_spectrum: 0.9311951238196343
typography_spectrum: 0.682876716600731
title: Actor Ben Kahre
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d1814'
    - '#4b3b21'
    - '#9a9c87'
    - '#f0bca4'
  brandStrength: 0.4635110206436366
  lightness: 0.7437562320847064
  saturation: 0.5614481891971081
  rhythmicContrast: 0.5310339187271893
purpose: []
