name: BenKahre
favicon: null
layout_spectrum: 0.9311951238196343
typography_spectrum: 0.50562
title: Actor Ben Kahre
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#222c31'
    - '#d5ad9d'
    - '#c8e6f1'
    - '#6f706b'
  brandStrength: 0.4635110206436366
  lightness: 0.7437562320847064
  saturation: 0.5614481891971081
  rhythmicContrast: 0.5310339187271893
purpose: []
