name: BenKahre
favicon: null
layout_spectrum: 0.9311951238196343
typography_spectrum: 0.50562
title: Actor Ben Kahre
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#969594'
    - '#1f201b'
    - '#616e61'
    - '#3c4339'
    - '#b27765'
  brandStrength: 0.4635110206436366
  lightness: 0.7437562320847064
  saturation: 0.5614481891971081
  rhythmicContrast: 0.5310339187271893
purpose: []
